language: go
go:
  - master

sudo: required

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libasound2-dev alsa-utils alsa-oss
  - sudo apt-get install libgl1-mesa-dev xorg-dev

after_success:
  - go get github.com/karalabe/xgo
  - pwd
  - xgo --targets=windows/*,darwin/* github.com/Humpheh/goboy